services:
  - type: web
    name: portal-academico
    plan: free
    region: oregon
    docker:
      dockerfilePath: Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: "Data Source=app.db"